### ISSUE TITLE
Object literal as argument when calling a function fails

### ISSUE THREAD

**Issue by eigilsagafos** [fauna/faunadb-js#169]
This query returns an error:
`q.Call(q.Function('my_function'), { foo: 'bar' })`

While this works.
`q.Call(q.Function('my_function'), q.Object({ foo: 'bar' }))`

In my particular case i want to send an array of objects to a function. My workaround is to wrap them with `q.Object()`.
`q.Call(q.Function('my_function'), [{foo: 'bar'}].map(item => q.Object(item)))`

**Comment by fauna-ryan** [comment]
Closing as stale/fixed. Please open a new issue if anything further is required. Thanks!
