### ISSUE TITLE
Tutorials link leads to 404

### ISSUE THREAD

**Issue by jonniebigodes** [fauna/faunadb-js#172]
While reading up on the documentation i was trying to access the tutorials section and the link redirected me to a 404. If possible please correct the actual tutorials endpoint address on the readme file on the repository, So that the actual tutorial is shown?

**Comment by BrunoQuaresma** [comment]
Hi @jonniebigodes, thanks for letting us know.

Those links can help you:
- https://app.fauna.com/documentation/crud-examples
- https://github.com/fauna/netlify-faunadb-todomvc
- https://github.com/fauna/todomvc-fauna-spa
- https://github.com/fauna/todomvc-fauna
