### ISSUE TITLE
Why are there duplicate functions?

### ISSUE THREAD

**Issue by ianwalter** [fauna/faunadb-js#176]
Specifically in query.js, there are duplicate functions with arbitrary code differences and/or doc comment differences. Why is this?

**Comment by trevorsibanda** [comment]
@ianwalter Can you provide more details and an example case in query.js ?

**Comment by ianwalter** [comment]
`ReplaceStr` for one but there are others.

**Comment by ianwalter** [comment]
Also I bring this up because when I tried to bundle this package with Rollup it errored out on these duplicate declarations.

**Comment by eigilsagafos** [comment]
I have the same issue. Juste opened a pull request. #178

**Comment by fauna-ryan** [comment]
Closing as stale/fixed. Please open a new issue if anything further is required. Thanks!
