### ISSUE TITLE
Request: Remove secret from errors

### ISSUE THREAD

**Issue by Flaque** [fauna/faunadb-js#185]
The secret is included in the `requestResult` of the error, which makes it extremely easy to accidentally log it or worse, include it in a result returned from the server. 

Could this not be the default behavior? It feels dangerous. 

Example:
```js
{
    "code": "INTERNAL_SERVER_ERROR",
    "exception": {
        "name": "BadRequest",
        "message": "invalid argument",
        "requestResult": {
        "client": {
            "_baseUrl": "https://db.fauna.com:443",
            "_timeout": 60000,
            "_secret": "fnADai1VTfACDkPxlleU2Ri_hoAthGp3Sph_J5J9", // HERE
            "_observer": null,
            "_lastSeen": 1571270077648626,
            "_keepAlive": {
            "_events": {},
            "_eventsCount": 1,
            "defaultPort": 443,
            "protocol": "https:",
            "options": {
                "keepAlive": true,
                "path": null
            },

...
```

**For any folks finding this from google:** my workaround at the moment is something like this:

```ts
import { omit } from 'lodash';

const formatError = err => omit(err, 'requestResult.client')
```

**Comment by BrunoQuaresma** [comment]
We are taking a look on this. Thanks @Flaque

**Comment by Flaque** [comment]
I'm pretty ignorant about all things security, so this might be nothing at all, but it looks like it's also leaking the SSL cert via the buffer in the `_sessionCache` variable. Again, that might be fine, but if it's not:

The `data` key appears to just be the raw data, which when converted to a `Buffer`, which if you convert it to ASCII appears to be the SSL cert. 

```js 
try {
  // some bad fauna query here
} catch(err) { 
  const arr = err
	  .requestResult
	  .client
	  ._keepAlive
	  ._sessionCache
	  .map["db.fauna.com:443::::::::::::::::::"]
	  .data

  console.log(Buffer.from(arr).toString('ascii'))
}
```

Again, no idea if this is as big of a danger as the secret's being leaked on errors.
