### ISSUE TITLE
Error trying to use in a Cloudflare Worker

### ISSUE THREAD

**Issue by yet-another-dev** [fauna/faunadb-js#207]
I'm seeing the following error while trying to use the driver in a [Cloudflare Worker](https://workers.cloudflare.com/): 

```
ReferenceError: XMLHttpRequest is not defined
```

This is making it impossible to use Fauna from Cloudflare Workers, unless there's some workaround that I haven't yet considered.

@aequasi [Sounds like](https://github.com/fauna/faunadb-js/issues/182#issuecomment-533427561) you're using Workers, are you seeing this issue?

Note: Originally opened this issue on the closed #182 but then realized it's likely best to create a new issue for it.

**Comment by lolcoolkat** [comment]
Bump! Also getting this error. Any ideas on how we can fix this! :) Thanks!

**Comment by lolcoolkat** [comment]
Update: Got it working on Cloudflare Workers :)

1) I had to remove the `cross-fetch` package (https://github.com/lolcoolkat/faunadb-js/commit/c2ad7a3e89ea3537888d8c9b7a1af12901aa8c91)

2) Also had to remove a little snippet at the bottom as it was giving an error as well (https://github.com/lolcoolkat/faunadb-js/commit/73ed874e796c1302e12f5d882c13c70edbdd3189)

I published the working version on NPM for the time being (so I could test it) https://www.npmjs.com/package/@snoculars/faunadb

Hopefully we can get these bugs fixed so I can use the official package again :D

**Comment by BrunoQuaresma** [comment]
Hi @lolcoolkat thanks for the fix. 

1. We used `cross-fetch` because some environments was having compatibility issues. So we need to find another solution instead of just remove it.

2. I have to check what it is doing.

**Comment by lolcoolkat** [comment]
@BrunoQuaresma Let me know if you have any time to look into a fix for this, or if you need me to work on this a bit? Would love to be able to use the official package soon at some point :D

**Comment by BrunoQuaresma** [comment]
@lolcoolkat NodeJS does not support `fetch()` natively so we need to use some polyfill like `cross-fetch` to make driver works on both environments (browser and nodejs). Unfortunately, we didn't find out a polyfill that was not using XMLHttpRequest however we are brainstorming to see what we can do about this issue so please, let us know if you have any ideas on your mind.

**Comment by eigilsagafos** [comment]
@BrunoQuaresma We use Axios in the browser and on our node backend. Have you considered using that?

**Comment by BrunoQuaresma** [comment]
@eigilsagafos I think axios uses XMLHttpRequests right?

**Comment by eigilsagafos** [comment]
Yeah... you are right. Was just looking at that.

**Comment by eigilsagafos** [comment]
I know some packages build for different environments and allow you to require like `require("fauna/browser")` and `require("fauna/node")`. Maybe you could even provide a barebones version where you could provide your own http adapter?

**Comment by BrunoQuaresma** [comment]
Yeah, we are thinking on this solution as well but it adds some extra effort to define a common API interface that should work for these environments. Sounds strange to me a  serverless environment does not support core NodeJS stuff.  🤔

**Comment by lolcoolkat** [comment]
@BrunoQuaresma Yeah Cloudflare Workers run ontop of V8 and without all the NodeJS overhead.. that's why they are super quick and performant! 

I'm wondering if we can add an extra config option when initializing the client perhaps?
```
var client = new faunadb.Client({ secret: 'YOUR_FAUNADB_SECRET', browser: true })
```

Doesn't have to be exactly like that, but hopefully you get the idea :D

**Comment by BrunoQuaresma** [comment]
> Yeah Cloudflare Workers run ontop of V8 and without all the NodeJS overhead.. that's why they are super quick and performant!

Cool, that make sense.

> Doesn't have to be exactly like that, but hopefully you get the idea :D And that config would allow you to specify whether to use cross-fetch or not?

I think it is a nice suggestion. We will evaluate that. Thanks for the contribution @lolcoolkat

**Comment by Ayplow** [comment]
Is there any reason `cross-fetch` doesn't just use the global `fetch` when it exists?

**Comment by sgehly** [comment]
Wow, thanks a bunch @lolcoolkat! Can't believe the one issue I was having was also the one open issue on this repo.

It also seems like a dependency for cross-fetch has an issue with webpack's require.

```
--> Error Message: "Uncaught ReferenceError: require is not defined
  at line 234485 in stream
  at line 20 in __webpack_require__
  at line 44296 in ./node_modules/node-fetch/lib/index.mjs
  at line 20 in __webpack_require__
  at line 12626 in ./node_modules/cross-fetch/dist/node-ponyfill.js
  at line 20 in __webpack_require__
  at line 14359 in ./node_modules/faunadb/src/Client.js
  at line 20 in __webpack_require__
  at line 14332 in ./node_modules/faunadb/index.js
  at line 20 in __webpack_require__
```

**Comment by lolcoolkat** [comment]
I've been thinking about this and I think a decent solution would be to allow a user to pass a `fetch` argument when initializing the Fauna Client. I think @eigilsagafos hinted at something similar. Something like the following:

```
var client = new faunadb.Client({ secret: 'YOUR_FAUNADB_SECRET', fetch })
```
Note the fetch included as an argument above ^ 

I think allowing a user to supply a fetch argument to use with the client would be great! You can check what is done here with `apollo-link-http` https://www.apollographql.com/docs/link/links/http They allow you to also pass your own `fetch` argument as well!

If no `fetch` argument is passed.. then the default `cross-fetch` library can be used. What do you guys think about this? @BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
@lolcoolkat yes it is! We just need to add some tests and an extra environment in our pipeline to check things on V8 environments. Thanks for the suggestion.

**Comment by BrunoQuaresma** [comment]
@lolcoolkat do you suggest any docker image to run V8 locally?

**Comment by lolcoolkat** [comment]
@BrunoQuaresma I guess we could close this issue now, with the fix in #214 

@yet-another-dev the fix will be available in the beta@release on **NPM** very soon. With the new `fetch` parameter you can can initialize the FaunaDB client in your Cloudflare Worker script like so:
```
const client = new faunadb.Client({
  secret,
  fetch: fetch.bind(globalThis)
})
```

**Comment by BrunoQuaresma** [comment]
Fixes on https://www.npmjs.com/package/faunadb/v/2.11.2-beta. We are releasing this soon on the main version.

**Comment by fireridlle** [comment]
just a small note. Cloudflare doesn't implement AbortController which we need to terminate requests as well as streams. so it better to pass customized fetch. for example:
```
            const client = new faunadb.Client({
                'secret': 'your secret',
                fetch: (url, params) => {
                    const signal = params.signal
                    delete params.signal
                    const abortPromise = new Promise(resolve => {
                        if(signal) {
                            signal.onabort = resolve
                        }
                    })
                    return Promise.race([abortPromise, fetch(url, params)])
                }
            })
```

**Comment by Mhmdrza** [comment]
> just a small note. Cloudflare doesn't implement AbortController which we need to terminate requests as well as streams. so it better to pass customized fetch. for example:
> 
> ```
>             const client = new faunadb.Client({
>                 'secret': 'your secret',
>                 fetch: (url, params) => {
>                     const signal = params.signal
>                     delete params.signal
>                     const abortPromise = new Promise(resolve => {
>                         if(signal) {
>                             signal.onabort = resolve
>                         }
>                     })
>                     return Promise.race([abortPromise, fetch(url, params)])
>                 }
>             })
> ```

this one actually works :O) previous solution fetch.bind(globalThis) Isn't work with fauna v4.x.x
