### ISSUE TITLE
Repo description misleading

### ISSUE THREAD

**Issue by yet-another-dev** [fauna/faunadb-js#208]
![image](https://user-images.githubusercontent.com/56443891/69769707-cc34a900-113a-11ea-9321-619c99edde5a.png)

> Node.js driver...

But the supported runtimes are more than just Node (https://github.com/fauna/faunadb-js#supported-runtimes).

Seems "Javascript driver" would be more accurate.

**Comment by BrunoQuaresma** [comment]
Done, thanks @yet-another-dev
