### ISSUE TITLE
src/Client.js:  missing quotes?

### ISSUE THREAD

**Issue by somev** [fauna/faunadb-js#212]
src/Client.js:223

```
      ...this._headers,
      Authorization: secret && secretHeader(secret),
      'X-FaunaDB-API-Version': APIVersion,
      'X-Fauna-Driver': 'Javascript',
      'X-Last-Seen-Txn': this._lastSeen,
```

Shouldn't  Authorization be within single quotes?

**Comment by BrunoQuaresma** [comment]
Hi @somev it is a valid JS syntax.

<img width="368" alt="Screen Shot 2019-12-26 at 10 06 34" src="https://user-images.githubusercontent.com/3165839/71477196-7ac61b00-27c7-11ea-8a2e-ee17a700dcaf.png">
