### ISSUE TITLE
connect ETIMEDOUT 52.214.123.134:443

### ISSUE THREAD

**Issue by hckhanh** [fauna/faunadb-js#219]
I really tired with this error: 
```
request to https://db.fauna.com/ failed, reason: connect ETIMEDOUT 52.214.123.134:443
```

Sometime I receive this!!!

**Comment by luukdv** [comment]
I'm getting similar errors from time to time:

`request to https://db.fauna.com/ failed, reason: write ETIMEDOUT`

`request to https://db.fauna.com/ failed, reason: socket hang up`

**Comment by BrunoQuaresma** [comment]
@hckhanh @luukdv This link https://docs.fauna.com/fauna/current/drivers/aws can be helpful.

**Comment by luukdv** [comment]
@BrunoQuaresma Perfect, thanks for the quick response!

**Comment by hckhanh** [comment]
Thank you for your response. I will close the comment with my code, so anyone else can make the right thing

```diff
-const { q, client } = require("./utils/fauna");
const { captureError } = require("./utils/sentry");

// a new client need to be initialized for every function handler
+const client = new faunadb.Client({
+  secret: process.env.FAUNADB_SERVER_SECRET
+})

exports.handler = async function(event, context, cb) {
  try {
    const clusterId = event.queryStringParameters["cluster"];
    const data = await client.query(
      q.Map(
        q.Paginate(
          q.Match(
            q.Index("rooms_by_cluster"),
            q.Ref(q.Collection("clusters"), clusterId)
          )
        ),
        q.Lambda(["name", "ref"], q.Get(q.Var("ref")))
      )
    );

    return {
      statusCode: 200,
      body: JSON.stringify(data)
    };
  } catch (e) {
    captureError(event, context, e);
    return {
      statusCode: 500,
      body: JSON.stringify(e)
    };
  }
};
```

This is the answer:
> We recommend that you create your client connection object within your handler functions so that you have a fresh connection object for each thawed context. All FaunaDB connections are light-weight HTTP connections,
