### ISSUE TITLE
Expose parseJSON

### ISSUE THREAD

**Issue by Akryum** [fauna/faunadb-js#222]
It would be useful if `parseJSON` was exposed so we can deserialize `Ref` object for example.

Current workaround:

```ts
import { parseJSON } from 'faunadb/src/_json'
```

**Comment by aputinski** [comment]
My use case is the server sending the serialized cursor down the client. To load the next page, I need to send the cursor back to the server deserialize it.

**Comment by BrunoQuaresma** [comment]
Internal card created https://faunadb.atlassian.net/browse/FE-324

**Comment by fauna-ryanharris** [comment]
@Akryum Thanks for the suggestion 🙌 As @BrunoQuaresma said, we've created a card for this internally. I brought it up to the team today and we'll take a look at putting it into an upcoming sprint.

**Comment by fauna-ryanharris** [comment]
@Akryum I am going to close this out since we have created a card and are now tracking this request internally. To keep up to date on its progress, check out our [Community Slack](https://join.slack.com/t/fauna-community/shared_invite/zt-8im8jvwn-i2KK6Inq~pYaRdXx74QWlg).
