### ISSUE TITLE
Release faundb source code  

### ISSUE THREAD

**Issue by mobop** [fauna/faunadb-js#224]
We want to use open source technology

**Comment by tylerhannan** [comment]
Thanks for opening the issue.

We have had a few internal discussions about open sourcing faunadb but, as you might imagine, that decision comes with a series of trade-offs and encompasses both technical and business considerations.

Put simply, at present there are no concrete plans to open source FaunaDB. 

It is, however, why we have the free tier. 'Open Source' is about a license...but also about an interaction model. You can interact with us & the community (here or in slack or etc). And you can try it without financial commitment.

Appreciate the perspective. Closing this for now.
