### ISSUE TITLE
Docs in TypeScript annotations

### ISSUE THREAD

**Issue by steida** [fauna/faunadb-js#234]
It would immensely improve DX. 

Btw, why this lib is not written in TypeScript? I can help you with design and transition. It's really worth it.

**Comment by fauna-ryanharris** [comment]
@steida Thanks for the note. We recently converted one of our private repos over to TypeScript and will potentially do the same here 👍

**Comment by steida** [comment]
@fauna-ryanharris Glad to hear it. I can't wait for properly typed everything :-) Btw, I am using Fauna with https://github.com/gcanti/io-ts, so all my TypeScript models are also runtime validated. It's super-awesome. Some examples are here: https://twitter.com/estejs
