### ISSUE TITLE
very confuse JSON response

### ISSUE THREAD

**Issue by danilockthar** [fauna/faunadb-js#235]
Im creating a collection in my code with something like the example in the docs:

q.CreateCollection({ name: 'users' })

the response in my api is :

{"error":"The \"string\" argument must be one of type string, Buffer, or ArrayBuffer. Received type undefined"}

but the collection its created anyway. i dont get that. if the collection is created successfully, why that message ?

then i create an Index  : 
q.CreateIndex(
        {
          name: "users_by_email",
          source: q.Collection("users"),
          terms: [{ field: ["data", "email"] }],
          unique: true
        })
Response : 
{"error":"The \"string\" argument must be one of type string, Buffer, or ArrayBuffer. Received type undefined"}

The index is created anyway the response. It is very confused to know if is success or not.

**Comment by marrony** [comment]
Can you provide more details about your environment? I'm asking because this error message is not produced by Fauna.

**Comment by danilockthar** [comment]
> Can you provide more details about your environment? I'm asking because this error message is not produced by Fauna.

Im in a local project in next js 9. Creating an api page in the new folder of  "/pages/api" 
sorry if that environment data its not enough, please be free to ask me what data do you need.

**Comment by marrony** [comment]
is it possible to log the exception captured to see its type and fields? this doesn't look a fauna exception.

**Comment by danilockthar** [comment]
> is it possible to log the exception captured to see its type and fields? this doesn't look a fauna exception.

How can i do that ? it doesnt goes to exception because the query is positive. It creates the index correctly with that message on screen.
im coming from php environment and this is new for me.

**Comment by marrony** [comment]
A `console.error(e)` on catch statement should be enough. This is where `{"error":"The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type undefined"}` is produced right?

**Comment by danilockthar** [comment]
> A `console.error(e)` on catch statement should be enough. This is where `{"error":"The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type undefined"}` is produced right?

I think is not, because if that is the case, the index and the collection , will not be created . It is correct ?

**Comment by danilockthar** [comment]
> A `console.error(e)` on catch statement should be enough. This is where `{"error":"The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type undefined"}` is produced right?

![faunaerro](https://user-images.githubusercontent.com/37883725/77083353-1e485580-69dc-11ea-8fa0-690f6153ed5b.png)

**Comment by marrony** [comment]
I cannot see the output of `console.error` on the print screen, only the stack trace

**Comment by danilockthar** [comment]
> I cannot see the output of `console.error` on the print screen, only the stack trace, can you scroll up a little bit? Or better yet, select all the output and paste here.

the console log is in my code, in the catch exception. and the output in screen is 
{"error":"The \"string\" argument must be one of type string, Buffer, or ArrayBuffer. Received type undefined"}
and in the console appears after " Wait compiling" and after Ready .

**Comment by marrony** [comment]
I need to see the output of the `console.error` not your code, your print screen shows a few lines of the output, but not all.

**Comment by evbruno** [comment]
```
///

res.status(200).json(dbs.data)
} catch (e) {
console.error(e);  /// <--- try adding this line to help debugging
// something went wrong
res.status(500).json({ error: e.message })
}
}
```

**Comment by danilockthar** [comment]
> ```
> ///
> 
> res.status(200).json(dbs.data)
> } catch (e) {
> console.error(e);  /// <--- try adding this line to help debugging
> // something went wrong
> res.status(500).json({ error: e.message })
> }
> }
> ```

Thats what i did. The output is in the cmd, not in the browser console. The browser console only print 500 internal error.  The output of that line in the catch is in the picture i posted..

**Comment by marrony** [comment]
that picture doesn't show the error, only the stack trace, would you mind and send another picture with the error. The error will be a colored json with some fields like `x-write-ops: ...`

**Comment by danilockthar** [comment]
> I need to see the output of the `console.error` not your code, your print screen shows a few lines of the output, but not all.
Im sorry but thats the only thing that output, the little piece above is previous output of repeated instace of index when i refresh my nextjs project.

step by step :
![output](https://user-images.githubusercontent.com/37883725/77088982-fc52d100-69e3-11ea-9c1d-1c4ba32fa2ec.png)

Then go to my page/api/name, refresh : 
![api string](https://user-images.githubusercontent.com/37883725/77089224-4fc51f00-69e4-11ea-9ef3-9702b0d335b1.png)

3- same stack trace on cmd, nothing on browser console.
4 - refresh again
5
![instaceerror](https://user-images.githubusercontent.com/37883725/77089350-7c793680-69e4-11ea-8f24-c1defb56cd1d.png)

6- Now my console show the catch error, because the index already exist, in the previous step it doesnt go to the catch. 
![xwrite-](https://user-images.githubusercontent.com/37883725/77089655-d974ec80-69e4-11ea-81f5-657ca761dc97.png)

The code doesnt go directy to catch (e) because create with success the index. the only problem is the message on screen.

**Comment by marrony** [comment]
the `BadRequest` error logged `console.log` is a Fauna error returned when you try to create the same schema 2 times, as per message `Index already exists`, this is kinda expected and should be handled correctly in your code.

The Buffer error you are reporting might be something related to the framework you are using, this is not related to Fauna.

**Comment by fauna-ryanharris** [comment]
@danilockthar Closing this out as it seems @marrony and @evbruno have addressed the issue 🙏
