### ISSUE TITLE
TypeScript version

### ISSUE THREAD

**Issue by steida** [fauna/faunadb-js#254]
Upcoming TypeScript version is a chance to do things right. Sure we can have typed API with TypeScript compiler checking the right composition, that's standard, but we should be able to enforce types even for runtime. Fauna is awesome but as any document DB, any shape approach can accidentally harm the developer. In the end, we need types. But can we blindly believe that our database will return what we expect? Never. Any serious application needs to validate/parse values out of the application boundary. Period.

That's why https://github.com/gcanti/io-ts is such an awesome library. Mature, well-tested, well-designed. 

I highly recommend to check it and use it for development TypeScript version of faunadb driver.

For example, this is the FaunaID type I am using. And I will need FaunaRef generic type. And types for Fauna errors. Etc.

```ts
interface FaunaIDBrand {
  readonly FaunaID: unique symbol;
}
export const FaunaID = t.brand(
  t.string,
  (s): s is t.Branded<string, FaunaIDBrand> => /^\d+$/.test(s),
  'FaunaID',
);
export type FaunaID = t.TypeOf<typeof FaunaID>;
```

I would love to help with any issue regarding TypeScript version design.

**Comment by steida** [comment]
Another example. Note serializeCookie signature requires FaunaSecret type. It can not accept a plain string. `t.type({ secret: FaunaSecret })` ensures via its decode method that we really got secret.

![Screenshot 2020-04-01 at 22 11 18](https://user-images.githubusercontent.com/66249/78182067-bf67ef00-7465-11ea-8019-d54b3b3e4036.png)

Maybe this stuff (Either) and algebraic types composition and functional domain modeling are new for you. It's much easier than it looks. And super useful. And available in TypeScript.

I highly recommend the first five minutes of this talk: https://www.youtube.com/watch?v=PLFl95c-IiU

**Comment by hasparus** [comment]
I'll just leave a note here.

I am aware that `io-ts` and fp-ts flavor functional API might not be for everyone.
I believe the idea of parsing data on application boundary to be sound regardless of preferred paradigm.

[**`ts-json-validator`**](https://github.com/ostrowr/ts-json-validator) is a nice alternative.

I'm using `io-ts`, but I wanted to present you with another option. 

#### Pros

1. It uses [ajv](https://github.com/epoberezkin/ajv), so it's crazy fast.
  ![image](https://user-images.githubusercontent.com/15332326/78186388-f2fa4780-746c-11ea-80e0-910d11757f40.png)
2. JSON Schema is pretty standard and the API might be more familar to some people.

#### Cons

There's a trade-off. It has 10x less stars and the API is subject to change.

---

_The attached chart is from [this benchmark](https://github.com/moltar/typescript-runtime-type-benchmarks)._

**Comment by steida** [comment]
The performance of io-ts is a non-issue. And nobody is supposed to be forced to use it. It's about how types should be defined. io-ts first ensures we can have reliable runtime-type checking for people who needs it. With Either. Performance micro-optimization is orthogonal.

**Comment by hasparus** [comment]
I've been using io-ts for over a year, you don't have to advertise it to me :D

> Note this can be easily ensured by io-ts.

This is checked by ts-json-validator **at runtime**.
_"Can't enforce using type system"_ means _"statically typechecked with type inferred from decoder"_.

All validating for refinement types must be done in userland at runtime unless there's been some recent development in [RSC](https://github.com/UCSD-PL/refscript).

> Check https://www.youtube.com/watch?v=PLFl95c-IiU

I watched this talk from NDC Sydney 2017. I really liked it :)
Did the 2019 version change a lot?

**Comment by steida** [comment]
Also, unnecessary instances and getters should really not be used. Getters are an anti-pattern for most cases.

**Comment by steida** [comment]
There is no will or resources to maintain Fauna driver and there is no competent maintainer so I am closing it. Too bad such great DB has such a terrible library.

**Comment by steida** [comment]
@hasparus Have you seen io-ts 3? https://github.com/gcanti/io-ts/pull/440#issuecomment-610343343
