### ISSUE TITLE
Why getters

### ISSUE THREAD

**Issue by steida** [fauna/faunadb-js#256]
I can understand it can be handy but they are not serializable to JSON and it can lead to confusing DX.

Is there any reason I am not aware of? Thank you

**Comment by marrony** [comment]
What getter are you talking about? Can you give an example?

**Comment by steida** [comment]
On the ref.

```ts
// [ 'value' ]
// 261926003610223115
console.log(Object.keys(pageDoc.ref));
console.log(pageDoc.ref.id);
```

**Comment by steida** [comment]
Ups. It's probably inherited. Hmm, maybe something wrong with my serialization, need to take a deeper look at driver source code.

**Comment by steida** [comment]
OK, it was getter :-) From my code:

```ts
// Not ideal, but let's wait for the new TS fauna driver API.
export const FaunaRef = t.type({
  id: FaunaID,
  // This will not work for indexes I think.
  // We will probably need some mapped type with id, type, name props.
  collection: t.type({ id: t.string }),
});
export type FaunaRef = t.TypeOf<typeof FaunaRef>;
```

And the driver source:

```js
/**
 * Gets the collection part out of the Ref.
 *
 * @member {string}
 * @name module:values~Ref#collection
 */
Object.defineProperty(Ref.prototype, 'collection', {
  get: function() {
    return this.value['collection']
  },
})
```

Serialization failed for some reason.

**Comment by steida** [comment]
I suppose the next version will not use defineProperty so it will be a non-issue.

**Comment by steida** [comment]
`Ref.prototype.toJSON` this was probably what broke my code.

**Comment by steida** [comment]
One would expect all Fauna JS models are serializable.

**Comment by steida** [comment]
For the sake of god, please do not use defineProperty nor toJSON. It sucks socks. Still fighting with the simple document serialization.

**Comment by steida** [comment]
So, I made wrapper types that allow to safely serialize and deserialize Fauna types.

https://github.com/typescript-fun/typed-functional-fauna
