### ISSUE TITLE
Do not override toJSON

### ISSUE THREAD

**Issue by steida** [fauna/faunadb-js#257]
It's super confusing that for a given object with some props, JSON.strinfigy produces an object with a different set of props. Also, I really don't see any reason to override toString but that's a minor issue.

It's hard to imagine anyone can use FaunaDB driver with this design. That's not how JavaScript/TypeScript should be written (classes, getters, toJSON/toString overrides). People serialize things all the time. With the current design, it's not even possible to serialize the simple document with Ref. 

Related to https://github.com/fauna/faunadb-js/issues/256, https://github.com/fauna/faunadb-js/issues/222, https://github.com/fauna/faunadb-js/issues/254

parseJSON really should not be required. Not at all and definitely not in the browser (I don't want to bundle the whole driver just for parseJSON). Hopefully, this will be addressed with the new TypeScript version.

Btw, if we really need a different type for serialization, for example, Date to a string, io-ts has a concept of Output type for such case. Check https://github.com/gcanti/io-ts-types/blob/master/src/DateFromISOString.ts

**Comment by steida** [comment]
OK. The workaround is impossible and I am overlooking something. At this point, it should be faster to rewrite Fauna driver from scratch than use it as designed. Damn.

**Comment by benjumanji** [comment]
You are more than welcome to rewrite the driver in your own image.
> It's hard to imagine anyone can use FaunaDB driver with this design.
Fortunately, you don't need to imagine it. We have people using it every day to build their businesses and their side projects alike. It's really great that you want to engage with us on driver design, but if you can't find a way to share your technical insight without the snark you'll probably find your issues and ideas ignored more often than you'd like.

**Comment by steida** [comment]
@benjitsu It's impossible to use a data library that produces unserializable models.

**Comment by benjumanji** [comment]
Evidently it is not, given that we have users today building on top of this driver. Issue closed. Come back when you can offer your technical expertise without the superfluous negativity.
