### ISSUE TITLE
Temp fix for unserializable models

### ISSUE THREAD

**Issue by steida** [fauna/faunadb-js#259]
Fauna driver uses models which are serialized into incompatible objects. For example, Ref id handled via getter is missing when a model is serialized. And we can not read serialized props until a model is serialized. It's like Catch-22.

The temporal fix is to use `JSON.parse(JSON.stringify(object))` to get plain row JSON without unserializable getters.

Hope this will help someone.

**Comment by marrony** [comment]
If you serialize and parse a json object that contains `@ref`, `@ts`, `@data` and `@query` fields using the native javascript you won't get the correct values, those attributes is part of our write protocol and this will not change anytime soon. Perhaps in the future we gonna adopt a binary protocol, so no JSON. The js-driver is a middleware that transform a DSL into raw bytes, by coincidence we choose JSON, but as I said, this can change to a binary format with no harm to the users.

What's the goal with this ticket? Make js driver adopt the best practices in js community? Make js driver adopt the best OO practices?

**Comment by steida** [comment]
My goal is very simple. I need to deliver data from Fauna to the browser through the server API.

In the server API, I call Fauna client.query. It returns some data. Those data are serialized to JSON with JSON.stringify. Those data contain Refs in the form of what Fauna client.query returns.

I need to read data from Fauna on the server, for example, to reuse created Ref, and I need the same shape on the client, for example, to reuse returned Ref.

As for "you shouldn't be serializing/deserializing our objects", does exist any other way to deliver data from Fauna client.query from the server to the client? 

Maybe I am overlooking something obvious for you, so please accept my apology if soo.

**Comment by steida** [comment]
I have to say I don't understand why you don't understand me. It's a super simple case. I have some data from Fauna, and I need to deliver them from the server to the client. It's super common. If JSON.stringify is prohibited, how we are supposed to deliver data to the client? And where it is described in the documentation? Thank you.

**Comment by marrony** [comment]
In that case you are free to use JSON.stringify, what I'm telling to you is that, you need to use our parser to reify the Fauna types (the one that contains fields `@`), otherwise when you send those types back to FaunaDB it won't be understood by the server, see https://github.com/fauna/faunadb-js/issues/222.

In the description of the issue you mentioned that "model" with getters were not being serialized correctly, well it is, maybe not the way you would expect, but this is part of our protocol. When I mentioned you shouldn't be serializing/deserializing it, or shouldn't be handling it directly is that you should tread a Ref as a String/Number and should not be using those getters, it's there for convenience case you need to access those attributes, but the best thing is to treat is as an opaque object, ie: with not fields.

**Comment by marrony** [comment]
I recommend you to join our [Fauna Community on Slack](fauna-community.slack.com) and have those discussions there, you will find many developers that already had those issues you are facing now.

**Comment by steida** [comment]
A protocol = serializable data. Getters are part of API we can not serialize it.

It's a design flaw. The current design forces developers to map Fauna Models manually just to be serializable. Imagine I am storing nested JSON with a lot of Refs. The current design forces me to create own transport format. That's very suboptimal and unnecessary I believe.

I don't want to import the whole Fauna library to the browser only to parse its model.
In JAM stack, it's super common to have the same model on the client and on the server so we can share functions, which is impossible with the current design, as I mentioned in the other issues.

**Comment by steida** [comment]
> but even in those cases we recommend process the object in the server side and return a raw object to your javascript code like:
> 
> var myId = await client.query(
>   Select('id', Ref(Collection('someCollection'), '123456789'))
> )

So every Fauna model must be manually processed to be serializable. Because you insist on bad and unnecessary design. OK.

**Comment by steida** [comment]
So, I made wrapper types that allow to safely serialize and deserialize Fauna types.

https://github.com/typescript-fun/typed-functional-fauna
