### ISSUE TITLE
I started an unofficial clone of Fauna JS driver

### ISSUE THREAD

**Issue by steida** [fauna/faunadb-js#260]
https://github.com/steida/faunadb-js

**Comment by danieltodonnell** [comment]
We appreciate your passion for our product and I look forward to what you are able to achieve.

Dan

**Comment by steida** [comment]
So, instead of an unofficial driver, I made wrapper types that allow to safely serialize and deserialize Fauna types.

https://github.com/typescript-fun/typed-functional-fauna
