### ISSUE TITLE
Client should handle errors like 413

### ISSUE THREAD

**Issue by eigilsagafos** [fauna/faunadb-js#263]
When the body becomes too large (1MB?) you get an 413 error returned from nginx with html in the body. The fauna client tries to parse the result as JSON resulting in a `Unexpected token < in JSON at position 0` error.

**Comment by fauna-ryanharris** [comment]
Hey, @eigilsagafos 👋 I am closing this out as we have created a card for it internally. We'll let y'all know when it's ready in Community Slack 🙏
