### ISSUE TITLE
Invalid argument for time zone designator without colon separator

### ISSUE THREAD

**Issue by minimaluminium** [fauna/faunadb-js#274]
```
q.Time('2019-05-27T05:15:48+0000')
```
It gives `Cannot cast \'2019-05-27T05:15:48+0000\' to a time.`, however, a time zone designator without a color separator seems like a valid ISO 8601 format.

[https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators](https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators)

```
q.Time('2019-05-27T05:15:48+00:00')
```

This one works though.

**Comment by fauna-ryanharris** [comment]
Thanks for reporting this issue, @minimaluminium 🙏 I'm going to bring this up to the team and create a ticket internally.

**Comment by fauna-ryanharris** [comment]
For your reference, the ticket is `DRV-171` 👍

**Comment by fauna-ryanharris** [comment]
@minimaluminium I am going to close this issue as we are now tracking it in our ticketing backlog. In the meantime, we are going to update our documentation to note this limitation. Thank you for reporting 🙏
