### ISSUE TITLE
queryTimeout not specified in QueryOptions interface

### ISSUE THREAD

**Issue by pchrapka** [fauna/faunadb-js#275]
When you specify a query with a timeout
`client.query(..., {queryTimeout: 1})`

I get the following typescript error
```
Argument of type '{ queryTimeout: number; }' is not assignable to parameter of type 'QueryOptions'.
  Object literal may only specify known properties, and 'queryTimeout' does not exist in type 'QueryOptions'
```

**Comment by fauna-ryanharris** [comment]
Thanks for reporting this, @pchrapka 🙏 I'll queue up a ticket to hit this.

**Comment by fauna-ryanharris** [comment]
@pchrapka I am closing this out as we have created a ticket for it and are tracking it internally 🙏 Feel free to join our [Community Slack](https://join.slack.com/t/fauna-community/shared_invite/zt-8im8jvwn-i2KK6Inq~pYaRdXx74QWlg) if you want to track its progress.
