### ISSUE TITLE
IE11 Polyfill 

### ISSUE THREAD

**Issue by jyk2000** [fauna/faunadb-js#284]
The doc only says it requires Promise Polyfill for IE11 support.
Can you give me more detail about  it? 

I've tried polyfil.io babel-polyfil but notthing worked.

**Comment by jyk2000** [comment]
The issue comes from use of "const" inside for-of in you lib.

**Comment by jyk2000** [comment]
It doesn't seem like any kind of polyfill fixes use of "const" inside for-of.

**Comment by BrunoQuaresma** [comment]
Hi @jyk2000 can you post the exact error message?

**Comment by jyk2000** [comment]
Unexpected identifier at .... 
 ex) for (const [x, y] of z)

**Comment by steida** [comment]
@BrunoQuaresma You will have to run Internet Explorer 11 (via a virtual machine or https://www.browserstack.com/) to test it anyway...

**Comment by jyk2000** [comment]
@BrunoQuaresma It's coming from src/Client.js at line 269. 
IE11 does not support for-of with const.

**Comment by jyk2000** [comment]
@BrunoQuaresma And polyfill doesn't seem like fixing the issue.

**Comment by steida** [comment]
@jyk2000 There is no polyfill for const, Fauna driver has to use compile target for IE11 which will transform const to var. Just out of curiosity, how do you consume the library?

**Comment by jyk2000** [comment]
@steida  So that means it can't be used in client side? 
I'm using polyfil.io + fauna in client side.

**Comment by steida** [comment]
How do you use Fauna? Src in the head? With bundler? Fauna works well on the client-side. Except for IE11 which is almost nobody using, that's why this bug was not reported earlier. The fix should be easy.

**Comment by jyk2000** [comment]
@steida Yeah fauna is working great in most browsers except IE11. 
We're healthcare publisher company and we still have a lot of doctors using IE which is our main clients.

**Comment by jyk2000** [comment]
@steida  Yeah just changing const to var works fine right?

**Comment by BrunoQuaresma** [comment]
@jyk2000 I think is not only change the var/const. Probably, we need to check all the other JS features which are not supported by IE11.

**Comment by parkhomenko** [comment]
Has been fixed for future versions of the library.
