### ISSUE TITLE
When is full text search wild card going in?

### ISSUE THREAD

**Issue by aprilmintacpineda** [fauna/faunadb-js#286]
According to docs https://docs.fauna.com/fauna/current/tutorials/indexes/search.html it currently doesn't have any, so if I choose faunadb for our app, how are we going to approach this?

I'm thinking of implementing a lambda function that receives all the results and filters them out, but I'm not so sure.

**Comment by steida** [comment]
@aprilmintacpineda Check https://fauna-community.slack.com/, there is a link to StackOverflow with a detailed description.

**Comment by aprilmintacpineda** [comment]
Hi Steida, I'm not in slack, how do I get an invite?

**Comment by BrunoQuaresma** [comment]
Hi @aprilmintacpineda you can take a look here https://community.fauna.com/

**Comment by aprilmintacpineda** [comment]
Yeah, it doesn't look like Fauna has a clear, documented way of doing it.
