### ISSUE TITLE
Observer option passed to query is not handled

### ISSUE THREAD

**Issue by steida** [fauna/faunadb-js#289]
This:

```js
if (self._observer != null) {
  self._observer(requestResult, self)
}
```

My use case is to create a default Client instance and pass the secret to the query method because of a different context. If I will add observer in the constructor, TypeScript type requires also a secret, which I don't have yet. 

A workaround is possible, but it would be better if the observer from query options would work.

```
var observer = self._observer || (options && options.observer)

if (observer != null) {
  observer(requestResult, self)
}
```

**Comment by BrunoQuaresma** [comment]
Sometime ago we had a discussion about this internally and I'll bring this up again. Thanks for let us know your use case.

**Comment by fireridlle** [comment]
Hi @steida . would that works for you?
https://github.com/fauna/faunadb-js/pull/402

note: an observer that passed to the Client constructor would be overwritten by an observer passed to the query.

**Comment by steida** [comment]
LGTM
