### ISSUE TITLE
Change in behavior between v2 & v3

### ISSUE THREAD

**Issue by ecwyne** [fauna/faunadb-js#326]
Testing this query: `And(Map([true, true, false], val => Not(val)))`

Using v2 returns `false`
Using v3 returns 
```json
Error: [
  {
    "position": [
      "and",
      0
    ],
    "code": "invalid argument",
    "description": "Boolean expected, Array provided."
  }
]
```

This caused production errors that I was able to mitigate by switching `And` to the preview function `All`

`And([true, true, true])` works in both versions, but mapping over the array causes the error

**Comment by nathaniel-may** [comment]
We have successfully reproduced this behavior internally and have identified a root cause. We will update when further action has been decided.

**Comment by n400** [comment]
Hi Eric. We're advising users switch to `All` if they run into this. We're also moving `All` out of "Preview" status as it is now stable for use in Production. Thank you!
