### ISSUE TITLE
Broken import in Hugo/esbuild

### ISSUE THREAD

**Issue by inwardmovement** [fauna/faunadb-js#331]
When importing the driver as an es6 module as per [the docs](https://docs.fauna.com/fauna/current/tutorials/crud?lang=javascript#import-the-driver) in a [Hugo](https://gohugo.io/) project (using [evanw/esbuild](https://github.com/evanw/esbuild) as the JS bundler) I have this error:

```
import faunadb, { query as q } from "faunadb"
console.log(faunadb);
console.log(q);
> JSBUILD: failed to transform "scripts/fauna.js" (application/javascript): Could not resolve "util"
```

When importing while hardcoding the path I've got this error:

```
import faunadb, { query as q } from "../../node_modules/faunadb/dist/faunadb-min.js"
console.log(faunadb);
console.log(q);
> Uncaught ReferenceError: q is not defined
> Uncaught ReferenceError: faunadb is not defined
```

Any idea how to solve that? At [Hugo](https://discourse.gohugo.io/t/jsbuild-could-not-resolve-util/27746) they say it might come from the way faunadb is packaged. Should I post an issue at [evanw/esbuild](https://github.com/evanw/esbuild) also?

**Comment by fireridlle** [comment]
Hello @inwardmovement. Sorry for the late response, we are going to be better and more active in issues)

Regards your issue, by default esbuild attempts to bundle all module dependencies. faunadb-js has some conditionally require like `if(nodejs) {require('util')}`, therefore esbuild tried to inject util module as well.

Here is PR that fixes this issue https://github.com/fauna/faunadb-js/pull/395. It's not released yet, however, you can clone it from the master branch.

Don't hesitate to contact us in case you faced any other issues
