### ISSUE TITLE
With large documents parsing streaming json fails

### ISSUE THREAD

**Issue by taylorjdawson** [fauna/faunadb-js#364]
This issue is that the stream is producing a chunk of the json file and if that chunk is not a complete json object this will fail. Now it looks like there is code in place [here](https://github.com/fauna/faunadb-js/blob/50a27fcf0395a673b2b8536183df670825b7dfc6/src/_json.js#L24) to be able to parse this streaming json data. 

I like the idea of parsing json as the chunks are streamed to reduce memory however, the current solution seems inadequate and a more robust solution might need to be implemented.

**Best Solution**: Stream the json from the backend via the [JSON Streaming protocol](https://en.wikipedia.org/wiki/JSON_streaming). This would send json objects in parseable chunks to alleviate the client side of having to deal with the broken json or needing to load it into memory before parsing it.

**Quicker Solution**: Wait until json object is complete before parsing although this would increase memory usage.

### Reproduction Steps
- Create a very large document on a collection 
- Write a small NodeJs script that listens to that document (the issue doesn't occur in the browser) and run it
- Modify the document in the dashboard or via another script
- You should see the error: `SyntaxError: Unexpected end of JSON input`

It looks like there is a missing case for this error in the `parseJSONStreaming` function:
```
    if (error.message.indexOf('JSON.parse') > -1) {
      var matchResult = error.message.match(/column ([0-9+]*)/)
      position = matchResult[1] - 1
      /** Firefox Syntax error message */
    } else if (error.message.indexOf('Unexpected token') > -1) {
      var matchResult = error.message.match(/at position ([0-9+]*)$/)
      position = matchResult[1]
    } else {
      throw error
    }
```

Additionally, this error message doesn't include the position where the error occurred.

**Comment by taylorjdawson** [comment]
@danieltodonnell Do you have a client side solution that I could help implement here?

**Comment by fireridlle** [comment]
The issue was that the server used to allow a max of 1 MB of the request payload. In case this limit exceeded, the server has responded with 413 Payload too large and HTML as content.
Currently, the server allows accepting higher request payload. I have tested with 3 MB and works for me

If you are still facing the same error, please create a separate issue with the code sample
