### ISSUE TITLE
Problems with stream.close()

### ISSUE THREAD

**Issue by PierBover** [fauna/faunadb-js#374]
I've found a couple of problems when using streams, all related to `stream.close()` on the browser.

The first one is that after using `stream.close()` it's not possible to restart the stream again with `stream.start()`. A new stream has to be created and started, otherwise this error is thrown:

> The stream has already been started.

If this by design the error should at least inform that a new instance has to be created on every subscription.

The second problem is that after using `stream.close()` the internal event listeners are not being cleared up properly.

I tried to subscribe to an inexistent document (on purpose to trigger errors) with the following error handler:

```
stream.on('error', (data, event) => {
	stream.close();
	setTimeout(() => {
		initStream();
	}, 250);
});
```

After the error is triggered, the current stream is closed and a new one is created on each retry. Since the document does not exist, a new stream is created every 250ms in a loop. As you can see from Chrome's dev tools, the event listeners keep growing continually even though the garbage collector has been clearing the heap regularly:

![image](https://user-images.githubusercontent.com/226483/102554850-35ab9080-408b-11eb-82c3-0542a1482404.png)

It could be I'm missing something, but from looking at [the source](https://github.com/fauna/faunadb-js/blob/master/src/stream.js), there doesn't seem to be a method to destroy the stream properly.

It's possible the issue is actually in the [polyfills of the Node libraries](https://github.com/fauna/faunadb-js/issues/361#issuecomment-747625270) the JS driver requires to work on the browser. OTOH it's quite strange that the end user has to provide polyfills to use the JS driver on a modern browser...

**Comment by tigger9flow** [comment]
@PierBover Hello! I just tried to profile it with my script, but listeners look fine in my case:

![image](https://user-images.githubusercontent.com/18001933/106791156-3c06c380-665d-11eb-89e8-24b623c6d899.png)

The code I ran:
```
const { query: Q, Client } = faunadb
const client = new Client({
  secret: '...',
})

let stream

const initStream = () => {
  stream = client.stream
    .document(
      Q.Ref(Q.Collection('categories'), '289059242399236612'),
    )
    .on('error', () => {
      stream.close()
      setTimeout(initStream, 250)
    })
    .on('snapshot', console.log)
    .start()
}

initStream()
```
Maybe you could share the full code snippet so I will try to reproduce it on my side?

**Comment by tigger9flow** [comment]
@PierBover Hi! I was investigating the issue and found that the problem is in Chrome DevTools itself, here's the link to the issue created in `fetch` repo: https://github.com/github/fetch/issues/901.
Here Google Chrome issue links:
https://stackoverflow.com/questions/46695853/javascript-listeners-keep-increasing
https://bugs.chromium.org/p/chromium/issues/detail?id=576302

**Comment by PierBover** [comment]
Thanks for checking it out @tigger9flow !
