### ISSUE TITLE
Unable to import into Cloudflare Workers

### ISSUE THREAD

**Issue by step135** [fauna/faunadb-js#375]
It worked in the past, not now. Using `import faunadb from 'faunadb'` is causing following error:

```
wrangler publish
✨  Built successfully, built project size is 44 KiB.
Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10021,
      "message": "Uncaught TypeError: Cannot set property 'AbortSignal' of undefined\n  at line 15\n  at line 1 in n\n  at line 15\n  at line 1 in n\n  at line 13\n  at line 1 in n\n  at line 13\n  at line 1 in n\n  at line 13\n  at line 1 in n\n"
    }
  ],
  "messages": []
}
```

**Comment by LeCodeCo** [comment]
I can replicate this issue. I've tried with both `import faunadb from "faunadb"` and `const faunadb = require("faunadb")` and building using `wrangler build` or `wrangler publish` works fine, but it cannot be uploaded/saved to Cloudflare because of the that error.

**Comment by jessepmason** [comment]
Same here, reverting back to npm 3.0.0 seems to work.

**Comment by jozsefm** [comment]
In my case, after switching back to npm 3.0.0 the wrangler-cli can't even execute publish anymore. @jessepmason what OS are you on? Is it really npm v. 3 that works for you?

**Comment by jessepmason** [comment]
Sorry about that! I meant reverting back the faunadb package to 3.0.0.

**Comment by eidam** [comment]
Yep, I can also replicate and the revert back to 3.0.1 helped.

**Comment by fireridlle** [comment]
Hello @step135. Sorry for the late response. Can you update `faunadb-js ` to version `4.0.2`. The issue should be fixed.  
Let me know if it still persists for you

**Comment by step135** [comment]
Yes, it is fixed. Thanks.

**Comment by fireridlle** [comment]
just a small note. Cloudflare doesn't implement AbortController which we need to terminate requests as well as streams. so it better to pass customized fetch. for example:
```
            const client = new faunadb.Client({
                'secret': 'your secret',
                fetch: (url, params) => {
                    const signal = params.signal
                    delete params.signal
                    const abortPromise = new Promise(resolve => {
                        if(signal) {
                            signal.onabort = resolve
                        }
                    })
                    return Promise.race([abortPromise, fetch(url, params)])
                }
            })
```
