### ISSUE TITLE
q.Call is not a function

### ISSUE THREAD

**Issue by hypervillain** [fauna/faunadb-js#376]
Probably a silly mistake on my side but I haven't been able to run a single query with both latest and v3 drivers. This is my code (Next.js API route):

```javascript
import faunadb from 'faunadb'

const client = new faunadb.Client({
  secret: 'XXX'
})

const q = client.query

export default async function query() {
  const response = await client.query(
    q.Call('get_paginated_submissions', ['285833526361719303'])
  )
  console.log({ response })
  return response
}
````

Error: `q.Call is not a function`. Am I missing something obvious?

**Comment by marrony** [comment]
Take a look on this page https://docs.fauna.com/fauna/current/drivers/imports?lang=javascript

**Comment by hypervillain** [comment]
🤦 thanks
