### ISSUE TITLE
Getting socket hang up error occasionally

### ISSUE THREAD

**Issue by robertsamarji** [fauna/faunadb-js#377]
Hello, I'm getting the following error message quite frequently:

`FetchError: request to https://db.fauna.com/ failed, reason: socket hang up`

There seems to be no pattern to the error. It occurs occasionally. Requests are being made from a server, not a lambda function, so I don't think the issue is related to lambda thawing.

For reference, I'm calling Fauna like so:

```
const faunadb = require('faunadb')
const q = faunadb.query
const { Create, Collection } = q

const Fauna = {}
const serverClient = new faunadb.Client({ secret: process.env.FAUNA_KEY_SECRET })

Fauna.createEntry = async (entry) => {
  try {
    await serverClient.query(
      Create(
        Collection('entries'),
        { data: entry }
      )
    )
  } catch (e) {
    console.log('createEntry error', e)
  }
}
```

I've since setup a retry mechanism, but I'd rather not have to rely on this. Does anyone know what's going on here / how to fix this?

**Comment by marrony** [comment]
Would you mind specify your environment? Also, in the meantime take a look on this page and if it can solve your problem https://docs.fauna.com/fauna/current/drivers/known_issues

**Comment by ecwyne** [comment]
@marrony 👆🏼this is news to me and very helpful. I've had ECONNRESET errors for a while and never knew why.

**Comment by robertsamarji** [comment]
Hi @marrony, I've come across this before. Unfortunately, I don't think it applies here as I'm not executing the code in an AWS lambda function. I've also tried moving the `serverClient` variable inside the `createEntry` function, but the _socket hang up_ errors still occur on occasion.

My environment is:

AWS EC2
App kept up with PM2
Node 8.9.4
faunadb ^3.0.1

**Comment by marrony** [comment]
This is the first time I'm reading about PM2, if I understood correctly PM2 is a daemon for nodejs, so I don't see any reason for the driver to give that error. Can you run the script locally? Does this happen only in daemon mode?

**Comment by robertsamarji** [comment]
@marrony Yes, I can run the app locally. I'm not sure sure if the socket hang up error occurs when running the app locally. I haven't seen it yet, but I don't send high volumes of requests when testing locally.

When being kept up by PM2, I may get 10 socket hang up errors (or on fewer occasions, timeout errors) for every 5,000 calls to Fauna to make a write.

I've implemented a retry mechanism as a workaround to minimise data loss. However, I haven't been able to work out why this is happening in the first place and how to minimise it?

**Comment by ygrik** [comment]
Hi @marrony 
I also have this socket issue
I use it with 
- Node v12.19.0 
- faunadb ^4.0.3

When I run my API with Express (API <-> FaunaDB) on the desktop it happens once in a while, but when another developer runs it on a laptop it happens more often. Most errors we see when run 5,000-10,000 calls to Fauna to read by index.
Maybe these details will help to improve the client code.

**Comment by n400** [comment]
@ygrik @robertsamarji Are you both still experiencing this with the most recent version of the driver (4.1.1)?

**Comment by n400** [comment]
This should be resolved with the most recent driver. Please let us know if you are still experiencing this and we will reopen this issue.
