### ISSUE TITLE
Child database for multi-tenancy app

### ISSUE THREAD

**Issue by dhnchandan** [fauna/faunadb-js#378]
I am trying to build a multi-tenancy app in FaunaDB. There is option of creating child databases from fauna shell. But my thinking is when a user is signed up, a child database with that username will create automatically. Is this possible to create a child database from JS directly?

**Comment by dhnchandan** [comment]
For every database we can create unlimited child database. We can create child database of the main database from fauna-shell. But I want to create child database from web front. When a user create new account, a child database with his username will create automatically. Is it possible?

**Comment by marrony** [comment]
See https://docs.fauna.com/fauna/current/api/fql/functions/createdatabase?lang=javascript
