### ISSUE TITLE
Missing type definitions for RequestResult

### ISSUE THREAD

**Issue by michaelmerrill** [fauna/faunadb-js#384]
The property definitions for [RequestResult](https://github.com/fauna/faunadb-js/blob/master/src/types/RequestResult.d.ts) are not fully defined. For example, the following code must be ignored due to `responseContent` being defined as `object`.

```(typescript)
const errors = error.requestResult.responseContent.errors;  // Property 'errors' does not exist on type 'object'.
```

**Comment by parkhomenko** [comment]
@michaelmerrill 
Your issue should be fixed in the latest version of the driver.
