### ISSUE TITLE
EventEmitter memory leak

### ISSUE THREAD

**Issue by eigilsagafos** [fauna/faunadb-js#408]
When running my test suite against 4.0.x my terminal is flooded with `MaxListenersExceededWarning` messages. I tracked it down to this line that I assume was introduced in version 4 of the driver: https://github.com/fauna/faunadb-js/blob/95aa75b8aa1b21d9f2f99cd3a468c13ef8690630/src/_http.js#L182

Node: I see that there are changes to how http is handled in Node in the making that might fix this issue?

**Comment by fireridlle** [comment]
Hello, @eigilsagafos . Is it possible to share code, so we can verify whether this issue still persist in http2 for nodejs

**Comment by eigilsagafos** [comment]
It happens when running our test suite with Jest. After a given number of requests I get two warnings logged for every fauna request.
```
(node:64339) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 response listeners added to [ClientRequest]. Use emitter.setMaxListeners() to increase limit
(node:64339) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [ClientRequest]. Use emitter.setMaxListeners() to increase limit
```

**Comment by fireridlle** [comment]
The team has been trying to reproduce this issue on our own tests as well as we have tried to create simultaneous connections. Also, we run the test from the repo https://github.com/shiftx/faunadb-fql-lib which you are contributing to. Unfortunately, we haven't got any memory leak warnings. With this in mind, I would like to enquire about the exact test suite one more time.

**Comment by eigilsagafos** [comment]
Hi, I can confirm that this has been "fixed" with the latest release of the driver when running on Node.js. (Due to http2 being used in Node.js and bypassing the "Safari" global hack here https://github.com/fauna/faunadb-js/blob/95aa75b8aa1b21d9f2f99cd3a468c13ef8690630/src/_http.js#L181)
