### ISSUE TITLE
http2 & net dependency not found

### ISSUE THREAD

**Issue by gregorvoinov** [fauna/faunadb-js#420]
Hi,

I have a fresh nuxtjs installation, that works. After installing faunadb I get the error message 
> This dependency was not found:
> http2 in ./node_modules/faunadb/src/_http/http2Adapter.js

next this one comes up, after installing http2
> This dependency was not found:
> net in ./node_modules/http2/lib/http.js

after installing net the page loads, but with this warning
> Critical dependency: require function is used in a way in which dependencies cannot be statically extracted_

my package.json
```
  "dependencies": {
    "@nuxtjs/axios": "^5.13.1",
    "@nuxtjs/pwa": "^3.3.5",
    "core-js": "^3.9.0",
    "faunadb": "^4.1.0",
    "http2": "^3.3.7",
    "net": "^1.0.2",
    "nuxt": "^2.15.1"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config": "^5.0.0",
    "@nuxtjs/eslint-module": "^3.0.2",
    "@nuxtjs/tailwindcss": "^3.4.2",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.20.0",
    "eslint-config-prettier": "^8.0.0",
    "eslint-plugin-nuxt": "^2.0.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.6.0",
    "prettier": "^2.2.1"
  }
```

**Comment by fireridlle** [comment]
the fix is on review, can you add the following code to your package.json
"browser": {"http2": false}

**Comment by gregorvoinov** [comment]
I deleted "node_modules" folder, added "browser": {"http2": false} to package.json and reinstalled everything, but didn't solved the problem. But if you are on it I will wait for the fix.

**Comment by impactvelocity** [comment]
Any ETA for the fix? I can't push anything, its preventing me from updating my app. :)

**Comment by parkhomenko** [comment]
hi @gregorvoinov @impactvelocity 
the 4.1.1 version is already in npm, could try to update it if you still experience your issue?

**Comment by impactvelocity** [comment]
Woo! It worked! :)

**Comment by gregorvoinov** [comment]
works. ;)
