### ISSUE TITLE
v4.1.1 Issue on Clouflare worker

### ISSUE THREAD

**Issue by richiedunk** [fauna/faunadb-js#437]
Hi,

I'm running v3.0.1 on a Cloudflare worker, no problems. Initialised like this...

```
import {Client, query} from "faunadb";

const faunadb = new Client({
  secret: 'ITS_A_SECRET',
  fetch: fetch.bind(globalThis)})
const q = query
```

When I upgrade to 4.1.1 I get the following error when trying an identical query. `The 'signal' field on 'RequestInitializerDict' is not implemented.`

Not sure if this is something you'd look into but thought I should flag it up.

**Comment by fireridlle** [comment]
hi @richiedunk . can you try the code described [here](https://github.com/fauna/faunadb-js#using-with-cloudflare-workers), please?

**Comment by richiedunk** [comment]
Ah yes, that works perfectly, thanks so much.

**Comment by PierBover** [comment]
@fireridlle is this a temporary workaround?

**Comment by fireridlle** [comment]
no, because cloudflare has its own implementation of fetch which doesn't support abort signal
