### ISSUE TITLE
FaunaError is not defined as type

### ISSUE THREAD

**Issue by Vadorequest** [fauna/faunadb-js#443]
![image](https://user-images.githubusercontent.com/3807458/111518325-41742500-8756-11eb-97d0-42c6bce2237b.png)

Using:

```ts
import { errors } from 'faunadb';
import FaunaError = errors.FaunaError;

export type OnStreamError = (error: FaunaError, restartStream: () => void) => void;

```

Currently, the class is defined but no types are being exported.
```ts
export module errors {
  export class FaunaError extends Error {
    constructor(message: string)

    name: string
    message: string
    description: string
  }
```

**Comment by Vadorequest** [comment]
Note the type should be:

```ts
export interface FaunaError extends Error {
  name: string;
  message: string;
  description: string;
}

```

That's what I created in my project for now and it works well.

**Comment by fireridlle** [comment]
Thank you. We track it internally as DRV-621

**Comment by tigger9flow** [comment]
Hi, @Vadorequest! This one seems to be a known issue (https://github.com/babel/babel/issues/7062) when using `import =` syntax with Babel. You could fix your code by either using destructuring assignment: `const { FaunaError } = errors` or accessing error class like this: `errors.FaunaError`.
We're planning to migrate to ES modules in the next major release and there will be no additional namespacing for members like error instances and others so you could `FaunaError` class from `faunadb`'s root:
```typescript
import { FaunaError } from 'faunadb'
```
