### ISSUE TITLE
returning @ts field instead of string field

### ISSUE THREAD

**Issue by theweiweiway** [fauna/faunadb-js#445]
Hi! Sorry if this is a very basic question - 

I'm using the faunadb driver on my node.js server to return a time field back to my client. The json that i receive in the client looks like this:
```js
birthday: {
  @ts: "2019-10-17T22:19:15.013Z"
}
```

However, I would like
```js
birthday:  "2019-10-17T22:19:15.013Z".        
```

I know I can easily just reassign the `birthday` variable, but I was wondering if there was a helper function in this library to return time fields as strings?

Thanks for the great driver!

**Comment by marrony** [comment]
you can wrap your date/time into a `ToString(...)` call, like
```
> ToString(Now())
'2021-03-22T21:13:09.485120Z'
```

**Comment by theweiweiway** [comment]
Sorry, I think I should have been more clear with my question

From the server, I'm getting a doc from the database which looks like:
```js
data: {
  name: 'name',
  email: 'email@hi.com',
  foo: 'bar',
  birthday: Time('2019-10-17T22:19:15.013Z')
}
```

After getting this doc in the server, I'm sending it to the client with `res.status(200).json(data)`. Then client is getting the birthday field in the `@ts` format, but I would like it just as a string.  

It's easy just to do `res.status(200).json({...data, birthday: data.birthday["@ts"]})`, but i have a lot of other documents with several time fields and I don't want to manually have to re-assign the field everyt time

**Comment by marrony** [comment]
Fauna doesn't provide an automatic way of doing this.

But you can write a recursive function on javascript and call it on the response data and convert all `FaunaTime` and `FaunaDate` types automatically for you (yes, dates will have `@date` tag)

**Comment by theweiweiway** [comment]
Basically loop through the keys, and if there is a `@date` or `@ts` field in it then reassign that field.

OK - thanks!
