### ISSUE TITLE
Version 4.1.2 dropped support for Client's param timeout

### ISSUE THREAD

**Issue by carloslenz** [fauna/faunadb-js#449]
This is a breaking change in a patch version, violating semantic versioning.

**Comment by fireridlle** [comment]
you need to use `queryTimeout` as they used to be the same

**Comment by carloslenz** [comment]
> you need to use `queryTimeout` as they used to be the same

I'm using it. The problem is breaking compatibility in a non major version. E.g, while 4.1.3 should still support both and only 5.0.0 should remove deprecated functionality.

**Comment by parkhomenko** [comment]
@carloslenz thanks for reporting this issue and sorry for the confusion, while you shouldn't have had issues keeping timeout as it was, we returned back the timeout as it was prior 4.1.2.
we'll update this field in the next major release as you suggested.
