### ISSUE TITLE
Importing `faunadb` breaks TS "dom" import - Cannot find name 'window'.  Cannot find name 'document'. Do you need to change your target library? Try changing the `lib` compiler option to include 'dom'.

### ISSUE THREAD

**Issue by Vadorequest** [fauna/faunadb-js#459]
I've been using faunadb successfully for weeks, but today I'm starting to use it in a new project and it breaks the whole project as soon as I import `faunadb`.

TS definitions related to the browser (e.g: `document`, `window`) are broken. I've looked around and this usually happens when the TS `lib` `dom` is not loaded, although I do import it in my `tsconfig.json`.

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/app/*": [
        "src/app/*"
      ],
      "@/common/*": [
        "src/common/*"
      ],
      "@/components/*": [
        "src/common/components/*"
      ],
      "@/utils/*": [
        "src/common/utils/*"
      ],
      "@/layouts/*": [
        "src/layouts/*"
      ],
      "@/modules/*": [
        "src/modules/*"
      ],
      "@/pages/*": [
        "src/pages/*"
      ]
    },
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "jsxImportSource": "@emotion/react",
    "lib": [
      "dom",
      "dom.iterable",
      "es2017"
    ],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "preserveConstEnums": true,
    "removeComments": false,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": false,
    "target": "ES2019"
  },
  "exclude": [
    ".github",
    ".next",
    "_site",
    "coverage",
    "cypress",
    "node_modules",
    "public"
  ],
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ]
}

```

Do you have any pointers as to why this would happen? I've tried importing other libs and only `faunadb` causes havoc. 

![Greenshot 2021-04-01 16 29 18](https://user-images.githubusercontent.com/3807458/113312782-ec661080-930a-11eb-96b5-45defc20fc5c.png)
![Greenshot 2021-04-01 16 30 09](https://user-images.githubusercontent.com/3807458/113312789-ed973d80-930a-11eb-940b-fa668a118184.png)
![Greenshot 2021-04-01 16 31 41](https://user-images.githubusercontent.com/3807458/113312792-ee2fd400-930a-11eb-8a2a-6a5341dec087.png)

**Comment by Vadorequest** [comment]
I found the root cause, it's because of the `cross-fetch` dependency.

It explicitely removes the lib.d.ts somehow with this:
```ts
/// <reference no-default-lib="true"/>
/// <reference path="./lib.fetch.d.ts" />
```

Importing `cross-fetch` causes the same issue, it's the real culprit here.
I've never seen a lib do that, it's really odd.

Full code:
```ts
/// <reference no-default-lib="true"/>
/// <reference path="./lib.fetch.d.ts" />

declare function _fetch(input: RequestInfo, init?: RequestInit): Promise<Response>;

declare var _Request: {
  prototype: Request;
  new(input: RequestInfo, init?: RequestInit): Request;
};

declare var _Response: {
  prototype: Response;
  new(body?: BodyInit | null, init?: ResponseInit): Response;
  error(): Response;
  redirect(url: string, status?: number): Response;
};

declare var _Headers: {
  prototype: Headers;
  new(init?: HeadersInit): Headers;
};

type _RequestInfo = RequestInfo
type _RequestInit = RequestInit

export {
  _fetch as fetch,
  _Response as Response,
  _Request as Request,
  _RequestInfo as RequestInfo,
  _RequestInit as RequestInit,
  _Headers as Headers,
}

export default _fetch

```

**Comment by fireridlle** [comment]
Thank you. We track it internally as DRV-618

**Comment by n400** [comment]
@Vadorequest I believe this was caused by an issue in the cross-fetch library, which they have since fixed: https://github.com/lquixada/cross-fetch/issues/104

Please let us know if you're still experiencing this after updating cross-fetch and we'll reopen the issue!
