### ISSUE TITLE
plans for distributing an ESM version

### ISSUE THREAD

**Issue by BetaConnector** [fauna/faunadb-js#463]
Hey - since vite does not support non-ESM libraries pretty well, there currently is no way using faunadb with svelte-kit + vite:
https://github.com/vitejs/vite/issues/2862

Are you guys planning to provide a ESM version?

Thanks in advance.

**Comment by n400** [comment]
Hi @BetaConnector. I've just created a [GitHub Discusssions thread](https://github.com/fauna/faunadb-js/discussions/469) with instructions on how to test the alpha version of our new JS driver, which would support ESM.

Would you be kind enough to try that out and see if it solves the issue you encountered? 

Meanwhile, I will close this issue and continue this conversation in the [GH Discussions topic](https://github.com/fauna/faunadb-js/discussions/469).

**Comment by ad6025b** [comment]
what is the status of this ESM version ?  can this be used in production?
