### ISSUE TITLE
Incorrect Error Type

### ISSUE THREAD

**Issue by brunosmm** [fauna/faunadb-js#497]
Hello,

Current and in the new version5.x.x, the FaunaHttpErrorResponseContent does not match with the return from FaunaDB.\

It's missing properties: 
- position
- cause (the most important for me)

Example of the error:
![image](https://user-images.githubusercontent.com/1554850/118409430-471cb700-b682-11eb-952f-e8cc28bd1730.png)

Without the cause, I am not able to identify the error I received from Fauna. In this case, I have an Abort transaction to return an error if the user does not exist and to do it I need to access the cause. 

Also would be really interesting to being the cause of a simple structure outside the responseContent, to access it I need to:
faunaError.requestResult.responseContent.errors[0].cause[0].code

**Comment by macnealefauna** [comment]
Hi Bruno, Thanks for the feedback. We are tracking work currently to improve the error messaging across the board for all of our drivers. We added this report to our internal tracking. Thanks for the report!

**Comment by brunosmm** [comment]
Thanks @macnealefauna, do you have an estimate for this fix?
Will be on 4.X version or only on 5.x?
