### ISSUE TITLE
Add option to skip driver version check?

### ISSUE THREAD

**Issue by leviwolfe** [fauna/faunadb-js#502]
I have just started seeing a ton of console log errors all over my unit tests, possibly due to #476? Could you add an option to skip this check, or possibly provide an alternative to using the console for this functionality?

Here's an example of my console output using jest during a single test called routes.test.js:
```

 PASS  src/api/v1/routes.test.js
  ● Console

    console.error
      Unable to check new driver version

      at ../../node_modules/.pnpm/faunadb@4.3.0/node_modules/faunadb/src/_util.js:519:15

    console.error
      FetchError {
        message: 'invalid json response body at  reason: Unexpected end of JSON input',
        type: 'invalid-json'
      }

      at ../../node_modules/.pnpm/faunadb@4.3.0/node_modules/faunadb/src/_util.js:520:15

```

**Comment by fireridlle** [comment]
option implemented. will be released as soon as possible.

just a small notice, it's just `console.error` log and shouldn't break any of your tests

**Comment by hugomrdias** [comment]
it throws an error basically making this package unusable
