### ISSUE TITLE
POST https://db.fauna.com/ net::ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by steida** [fauna/faunadb-js#508]
Why did this error happen? 

![Screenshot 2021-06-25 at 22 47 28](https://user-images.githubusercontent.com/66249/123483775-9225d480-d607-11eb-8fe9-08e5395d1f92.png)

**Comment by macnealefauna** [comment]
There isn't anything we can reproduce on this. It looks like there was a network error. If you could be more specific about what you expect to see here, please let us know.
