### ISSUE TITLE
UDF fails to execute

### ISSUE THREAD

**Issue by PierBover** [fauna/faunadb-js#510]
Whenever I use a UDF with the JS driver I'm getting this error:

```
[InvalidValue: Provided Function must take at least 1 argument.] {
  description: undefined
}
```

This is the query:

```
Let(
    {
        indexRef: Index('Audios_by_ownerRef_values'),
        values: Select(
            'data',
            Paginate(Match(Var('indexRef'), Ref(Collection('Users'), '302123890483659266')))
        )
    },
    Call(Function('GetIndexValuesObject'), [
        Var('indexRef'),
        Var('values')
    ])
)
```

If I copy and paste the exact same query in the shell it works fine (obviously using the same role):

![image](https://user-images.githubusercontent.com/226483/128407619-a7eaf1e9-76fb-4eb5-b6bb-3bf7c8995d9a.png)

* Node 14.15.4
* faunadb 4.3.0

**Comment by faunaee** [comment]
How have you imported the Fauna driver?

If you use the standard import statements (that all of the JavaScript examples in the documentation use):
```
const faunadb = require('faunadb')
const q = faunadb.query
```

Then all of the FQL statements require the `q.` prefix. For example `q.Let(...)`. Your query doesn't include that, so are you importing all of the FQL functions into the global namespace?

**Comment by PierBover** [comment]
I simply import every function I need for the current file as it makes the FQL code cleaner.

Eg:

```js
const {Create, Collection, CurrentIdentity} = faunadb.query;
```

It's how I have been doing it in all the JS tutorials I've written for Fauna too.

**Comment by faunaee** [comment]
Thanks!

This query is similar, conceptually, to what your query is doing, and it uses the demo data available when you create a new database:

```
client.query(
  q.Let(
    {
      values: q.Select(
        ["data"],
        q.Paginate(q.Match(q.Index("products_by_price_high_to_low")))
      )
    },
    q.Map(
      q.Var("values"),
      q.Lambda("X", q.Call("double", q.Select(0, q.Var("X"))))
    )
  )
)
.then((res) => console.log(res))
.catch((err) => console.log(err))
```

For me, no error occurs and I see this output:

```
[
  49.98, 47.98, 13.96,
   9.98,  7.98,  6.98,
   5.98,  2.98,   0.7
]
```

Since you say that you get the error with any UDF called via JS, it would be helpful to know whether this example works for you.

**Comment by PierBover** [comment]
The issue is definitely not in the query itself. If I remove the calls to the UDF everything works as expected.

Here's the code for the UDF I'm using:

https://gist.github.com/PierBover/b582a229e30b2edb368587635a057e4d

For more context on the function here's a post on the forum:

https://forums.fauna.com/t/how-to-combine-two-arrays-to-use-with-toobject/2331

I'm going to try creating a small repro project so you can better debug this. Otherwise I think it's going to be too complicated.

**Comment by faunaee** [comment]
Looking at your UDF, I can see 4 nested Lambda functions. Any one of those could provide the error that you are reporting. 

Can you provide the full output of the `responseContent` field from the response? That contains information about the position of the error, which would help determine which embedded function might be complaining about parameters. For example, in the query I provided, if I change the `Call` expression to:

```
q.Call("double", 1, q.Select(0, q.Var("X")))
```

I get this in the response's `responseContent` field:

```
    responseContent: {
      errors: [
        {
          position: [ 'in', 'map', 'expr' ],
          code: 'call error',
          description: 'Calling the function resulted in an error.',
          cause: [
            {
              position: [ 'expr', 'add', 0 ],
              code: 'invalid argument',
              description: 'Number expected, Array provided.'
            },
            {
              position: [ 'expr', 'add', 1 ],
              code: 'invalid argument',
              description: 'Number expected, Array provided.'
            }
          ]
        }
      ]
    },
```

The `position` field is telling me that the error occurs in the `in` (the second argument to `Let`), `map`, `expr`. Here `expr` refers to the `Call` expression. And the `cause` field tells me that the problem(s) are in `expr`, `add`. This second `expr` refers to the Lambda in the UDF, which uses `Add`.

**Comment by PierBover** [comment]
Ok I figured out what was going on.

I forgot to reference the FQL `Function', and since there is a native [Function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function) type in JS, that's what the JS engine was using which probably caused all sorts of unexpected issues.

It probably wasn't a great idea to name FQL functions in the JS driver just like native JS types (`Function`, `Map`, etc).

Sorry for wasting your time Ewan.
