### ISSUE TITLE
Allow to use AbortController

### ISSUE THREAD

**Issue by steida** [fauna/faunadb-js#511]
A feature request. It would be great if the Fauna driver would support AbortController.

**Comment by steida** [comment]
Hmm, fetch param in options does not work, but AbortControler signal is passed!

Docs should be updated.

**Comment by fireridlle** [comment]
@steida can you share code, please

**Comment by steida** [comment]
@fireridlle My use case was a toggling button with an optimistic update. The only correct approach is AbortController, I tried several "smart" JS-only tricks, nothing worked. AbortController is 💯

As you can see, the only thing I need is to pass the current signal and abort the previous.
askToBorrowMutation is a functional wrapper over Fauna client.

Elsewhere: `client.query(expr, { signal })` Note this is not supported by Fauna TS types.

```ts
const ctrlRef = useRef<AbortController | null>(null);

const handleItemPress = () => {
  switch (thing.state.type) {
    case 'available': {
      updateThingStateType('asked');
      if (ctrlRef.current) ctrlRef.current.abort();
      ctrlRef.current = new AbortController();
      askToBorrowMutation.commit(ctrlRef.current.signal);
      break;
    }
    case 'asked': {
      updateThingStateType('available');
      if (ctrlRef.current) ctrlRef.current.abort();
      ctrlRef.current = new AbortController();
      cancelAskToBorrowMutation.commit(ctrlRef.current.signal);
      break;
    }
    case 'borrowed':
      break;
    default:
      absurd(thing.state);
  }
};```

**Comment by fireridlle** [comment]
So, the issue here is only types?

**Comment by steida** [comment]
Yep.
