### ISSUE TITLE
Streams support in Docker Fauna for local dev

### ISSUE THREAD

**Issue by TimPchelintsev** [fauna/faunadb-js#513]
Hi! Maybe not the best place to ask this question but I have no idea what is the right place for Docker Fauna...

So, I have a project based on Fauna deployed to the cloud, but development is maid against local Docker Fauna, which is very convenient for TDD. Today I tried to implement document stream support for chat and have a problem - it seems stream is established, but no 'start', 'snapshot' or 'version' events coming. At the same time, if I pass  a non-existent collection name or document id in Ref passed to client.stream.document(...), it fires 'error' event. So I am a bit confused - will be very grateful if someone can help.

Code is like this:
```javascript
class FaunaStream {
  constructor ({ id, collection, client }) {
    this.docRef = q.Ref(q.Collection(collection), id)
    this.client = client
    this.initStream()
  }

  initStream () {
    this.stream = this.client.stream.document(this.docRef)
      .on('start', () => console.log('STREAM STARTED EVENT'))
      .on('snapshot', (data, event) => console.log('SNAPSHOT', data, event))
      .on('version', (data, event) => console.log('VERSION', data, event))
      .on('error', () => console.error('STREAM ERROR !!!'))
      .start()
```

**Comment by fireridlle** [comment]
Streaming is not enabled by default.

in the config file
```
stream_enable_api: true
```

and then mount it (change paths to what you have):
```
docker run --rm --name faunadb -p 8443:8443 -p 8084:8084 \
  -v /home/agourlay/Workspace/faunadb-docker.yml:/fauna/etc/agourlay-config.yml \
  gcr.io/faunadb-cloud/faunadb/enterprise/nightly:latest \
  --config /fauna/etc/agourlay-config.yml
```

**Comment by TimPchelintsev** [comment]
Hi! Thank you for the answer. I followed your instructions, provided custom config so I can
check it is being used seeing `Cluster name: faunastreams` in the logs because of the line
`cluster_name: faunastreams` in custom config file instead of default "fauna". 

For sure I provided `stream_enable_api: true` in same config file.

Faunadb was so kind that even merged my config with default, giving me this at the end:

```
---
accelerate_indexes: true
auth_root_key: secret
cluster_name: faunastreams
http_max_concurrent_streams: 100
log_path: /var/log/faunadb
network_admin_http_address: 127.0.0.1
network_broadcast_address: 172.18.0.2
network_coordinator_http_address: 0.0.0.0
network_listen_address: 172.18.0.2
shutdown_grace_period_seconds: 0
storage_data_path: /var/lib/faunadb
stream_enable_api: true
```

**But still no luck with local streams.** They worked like a charm in production, though! So maybe I still missed something? It will be definitely cool to be able to test streams locally, because I can initiate object updates in Cypress test with custom command and then check UI changes.

**Comment by TimPchelintsev** [comment]
I should mention that I obviously don't have permissions to use gcr.io/faunadb-cloud/faunadb/enterprise/nightly:latest and use standard https://hub.docker.com/r/fauna/faunadb as mentioned in the docs https://docs.fauna.com/fauna/current/integrations/dev

**Comment by fireridlle** [comment]
are you using the latest version. i just got an answer that `21.05.04-72399a3`  (that is the latest,  docker image) has enabling streams by default

**Comment by TimPchelintsev** [comment]
So I updated to new version 4.2 from DockerHub, and in Dockerfile it has this line:
`LABEL faunadb.version=21.08.00 faunadb.package=21.08.00-0`

But unfortunately, no luck with local streams support.
