### ISSUE TITLE
[Question] Cloudflare Worker // esmodule

### ISSUE THREAD

**Issue by domsen123** [fauna/faunadb-js#516]
Hi,

I am not able to get an working project with vite/faunadb...

I've used this "starter template" [Vitessedge](https://github.com/frandiox/vitessedge-template)

I am getting this error on build:
```bash
[commonjs] Unexpected token (245:34) in /home/dmarx/projects/vitessedge/vitessedge-fauna/node_modules/faunadb/src/_util.js
file: /home/dmarx/projects/vitessedge/vitessedge-fauna/node_modules/faunadb/src/_util.js:245:34
243:     {
244:       name: 'Netlify',
245:       check: () => process.env.hasOwnProperty('NETLIFY_IMAGES_CDN_DOMAIN'),
                                       ^
246:     },
```
on this code I used as endpoint

```javascript
const secret = import.meta.env.VITEDGE_FAUNA_SERVER_KEY as string
const client = new Client({ secret, keepAlive: false })
```

I think this is some esmodule/commonjs problem?!

I dont know - do you have any hints?!

**Comment by fireridlle** [comment]
@domsen123 I have tried with a fresh copy of `Vitessedge` and have no issue. Tried init client from both be and fe code.
Could you provide minimum repo that reproduce your issue and share nodejs & faunadb versions

**Comment by domsen123** [comment]
@fireridlle here you go [vitessedge-fauna](https://github.com/domsen123/vitessedge-fauna)
