### ISSUE TITLE
Corrupt data on the US replica(s)

### ISSUE THREAD

**Issue by hazae41** [fauna/faunadb-js#541]
When doing a simple map-with-paginate query from a Vercel serverless function, some entry appears twice.

My raw query: 
```json
{"map":{"lambda":["_","ref"],"expr":{"select":["data","name"],"from":{"get":{"var":"ref"}}}},"collection":{"paginate":{"match":{"index":"last_forums"},"terms":[]},"size":20}}
```

When executed in Vercel (Next.js app):
![Capture](https://user-images.githubusercontent.com/4405263/135785560-dc21404f-089c-419b-afae-db63e24a5c94.PNG)

When executed locally in terminal:
![Capture](https://user-images.githubusercontent.com/4405263/135785715-249bd926-a36b-4740-8f83-ca00a75a0ac1.PNG)

This is the same query, but the Vercel one returns 13 entries instead of 12, with a duplicate: "blabla".

When running my Next.js app locally, the bug is not there, it only happens when my app is deployed.

The code running on Vercel is just:
```typescript
console.log(query)
const data = await fauna.query(query)
console.log(data)
```

Using faunadb@4.4.1

**Comment by fireridlle** [comment]
that strange. does your code points to the same database from local & netlify instances? 
how does your index look like?
can you run a simple Paginate query without mapping it. just to ensure that references are different

**Comment by hazae41** [comment]
References are definitely the same
![Capture](https://user-images.githubusercontent.com/4405263/135891544-76e57af1-ba93-4d48-b4f9-90a157e1c0d2.PNG)
When parsed:
![Capture](https://user-images.githubusercontent.com/4405263/135891394-1d6b17ed-f149-4b1c-9859-dc6d118b8d53.PNG)

**Comment by hazae41** [comment]
But times aren't, the second entry is stuck at the epoch second `1633040906`. Even when updating the document and changing the `updated_at` field, the second entry keeps displaying `1633040906`, while the first is correctly updated.

**Comment by hazae41** [comment]
The bug is still there when using an `observer` for the HTTP response. `responseRaw` also has the duplicated entry.
![Capture](https://user-images.githubusercontent.com/4405263/135895212-08278e5c-27a3-4fba-a62a-9484fae94b30.PNG)

**Comment by hazae41** [comment]
I think the bug comes from a mismatch between the US and EU servers. 
I'm using the Classic region group, my Vercel function is located in US, while I'm located in Europe. 
This could explain why I don't get the same results when deploying my app.

So there is a bug with my database on the US replica(s?). Why? Is there a way to reset the US replica(s)?

**Comment by steida** [comment]
@hazae41 Fauna is broken like Facebook today (read, many hours)

https://status.fauna.com/

**Comment by marrony** [comment]
@hazae41 you can connect direct to EU region group using the endpoint db.eu.fauna.com

**Comment by hazae41** [comment]
> @hazae41 you can connect direct to EU region group using the endpoint db.eu.fauna.com

Thanks but it throws 401 Unauthorized as my database is setup for Classic and not Europe

**Comment by hazae41** [comment]
Maybe Fauna should show this kind of problems on the dashboard in addition to the status website. This could save its customers many hours of useless debugging.
