### ISSUE TITLE
Generated JSDoc hosted on github.io has many broken links

### ISSUE THREAD

**Issue by leviwolfe** [fauna/faunadb-js#578]
There are several links to https://fauna.github.io/faunadb-js/ in the [readme for the faunadb-js repo](https://github.com/fauna/faunadb-js/blob/6ea18e9c8881896e0f14af9b05e0113d0d85b916/README.md?plain=1#L11). Unfortunately, many of the links no longer work. It seems like almost every class/module linked directly on the https://fauna.github.io/faunadb-js/ homepage is now a 404. Here's a few examples:

- Client: https://fauna.github.io/faunadb-js/Client.html
- query: https://fauna.github.io/faunadb-js/module-query.html
- PageHelper: https://fauna.github.io/faunadb-js/PageHelper.html

**Comment by grempe** [comment]
Came here to report the same. The JS Documentation links are all non-functional.

**Comment by rts-rob** [comment]
Release 4.4.2 resolves this issue. Thank you for reporting @leviwolfe
