### ISSUE TITLE
Problem with Join/Singleton

### ISSUE THREAD

**Issue by terazus** [fauna/faunadb-js#620]
Hello dear Fauna dev,
I'm trying to implement a Join arround the output of a query in order to only return the ref through a singleton.
I followed the tutorial here: https://stackoverflow.com/questions/69065039/how-to-querying-and-filtering-efficiently-on-fauna-db/71189426#71189426

I've run the following command in my fauna dashboard and it works correctly 
```
Paginate(
  Join(
    Range(Match(Index('ExpensesByPrice')), [], 100),
    Lambda(['price', 'ref'], Singleton(Var('ref')))
  )
)
```

However, when I try create the equivalent JS code, it returns an empty array;
```js
const resp = await CLIENT.query(
    q.Paginate(
      q.Join(
        q.Range(q.Match(q.Index('ExpensesByPrice')), [], 100),
        q.Lambda(['price', 'ref'], q.Singleton(q.Var('ref')))
      )
    )
  )
  console.log(resp)
```
For info, i'm trying to create an interception between two indexes that return a different shape.
Could someone tell me what's wrong with my code?

Thx :)

**Comment by faunaee** [comment]
The code looks fine. Is your code accessing the same database? In the same region group? If so, are you using a secret that has privileges to read the `ExpensesByPrice` index?

Note that the [Forums](https://forums.fauna.com/) are a better place to inquire about coding problems that aren't (necessarily) bugs in the JavaScript driver.

**Comment by terazus** [comment]
Hello,
It's the same DB and I'm using the admin key to bootstrap my database.
I'll move the question to the forums so I can close the ticket.

Thx.
