### ISSUE TITLE
"invalid ref" when using `client.query( Create( Collection('test') ...`

### ISSUE THREAD

**Issue by da99** [fauna/faunadb-js#645]
My setup:

-  Node: v18.4.0
-  FaunaDB driver: 4.6.0

Code (example from README.md):

```javascript
var createP = client.query(
  q.Create(q.Collection('test'), { data: { testField: 'testValue' } })
)
```

Result: 
```bash
  error: 'invalid ref'  
  stack: |-
    FaunaHTTPError.raiseForStatusCode (.../node_modules/faunadb/src/errors.js:158:15)
    Client._handleRequestResult (..../node_modules/faunadb/src/Client.js:385:25)
    ...node_modules/faunadb/src/Client.js:347:12

```
The problem seems to be using a `Collection` object as an argument to `Create`. 

If I use `CreateCollection` instead of `Create(Collection(...), ...)` it works:
```javascript
var createP = client.query(
  q.CreateCollection({ name: 'test', data: { testField: 'testValue' } })
)
```

**Comment by faunaee** [comment]
@da99 Did the collection exist when you ran the first query? If not, the error is correct. Your query attempted to create a document within the `test` collection when that collection did not exist.

You _can_ use `Create` to create a collection:

```
q.Create(q.Collections(), { name: "test" })
```

That is equivalent to:

```
q.CreateCollection({ name: "test" })
```

**Comment by da99** [comment]
You're absolutely right. Stupid me for not seeing the obvious. Thanks so much.
