### ISSUE TITLE
Is it safe to expose the key in the browser?

### ISSUE THREAD

**Issue by rafbgarcia** [fauna/faunadb-js#670]
The [browser documentation](https://github.com/fauna/faunadb-js#use) says we should expose the key in the HTML, is that safe?

**Comment by ptpaterson** [comment]
If you intend your key to be public, then yes: there is no problem with sharing the key in your html.

Beyond that, the example is to quickly demonstrate that the driver can be used in the browser. If necessary for your application, please do follow best practices for securing your secrets. We have some "[blueprints](https://github.com/fauna-labs/fauna-blueprints/tree/main/official/auth)" that demonstrate this better, but are too verbose to provide in the driver's README.

**Comment by rafbgarcia** [comment]
Thank you @ptpaterson
