### ISSUE TITLE
what is the status of the ESM driver? 

### ISSUE THREAD

**Issue by ad6025b** [fauna/faunadb-js#681]
what is the status of the ESM driver? https://github.com/fauna/faunadb-js/discussions/469
 ==> can this be used in production>

**Comment by ptpaterson** [comment]
We have yanked and removed the v5 alpha driver. We do not intend to release it. We will be maintaining this v4 driver while moving forward with our v10 driver in a different repository here: https://github.com/fauna/fauna-js
